banking-system-master/accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
]

banking-system-master/banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

banking-system-master/transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
]

banking-system-master/core/models.py
from django.db import models

# Create your models here.

banking-system-master/core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'core/index.html'

banking-system-master/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Dummy Banking System" />
        <meta name="author" content="Maksudul Haque" />
        <title>
            {% block head_title %}Banking System{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block head_extra %}{% endblock %}
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>
</html>

banking-system-master/templates/core/footer.html
<footer class="footer bg-gray-200 relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-6">
                <p class="text-md text-gray-900 font-bold mb-2">
                    © 2020 by <a href="https://github.com/saadmk11" target="_blank">saadmk11</a>
                </p>
            </div>
        </div>
    </div>
</footer>

banking-system-master/templates/core/index.html
{% extends 'core/base.html' %}

{% block head_title %}Banking System{% endblock %}

{% block content %}
    <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
        <!--Left Col-->
        <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-12 pb-24 px-6">
            <h1 class="font-bold text-4xl my-4">Banking System</h1>
            <p class="leading-normal mb-4">
                This is an Example web application created using django.
                You can find the sourse code on <a href="https://github.com/saadmk11/banking-system">GitHub</a>
            </p>
            <div>
            <a href="{% url 'accounts:user_registration' %}" class="bg-transparent hover:bg-gray-800 text-gray-800 hover:text-white rounded shadow hover:shadow-lg py-2 px-4 border border-gray-900 hover:border-transparent">Register</a>
            <a href="https://github.com/saadmk11/banking-system" class="bg-transparent hover:bg-gray-800 text-gray-800 hover:text-white rounded shadow hover:shadow-lg py-2 px-4 border border-gray-900 hover:border-transparent">GitHub</a>
            </div>
        </div>
        <!--Right Col-->
        <div class="w-full lg:w-1/2 lg:py-6 text-center">
            <h1 style="font-size: 12rem" class="font-black text-gray-800">$$$</h1>
        </div>
    </div>
{% endblock %}

banking-system-master/templates/core/messages.html
{% for message in messages %}
<div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
    <div class="flex">
        <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
        <div>
            <p class="font-bold">Success!</p>
            <p class="text-sm">{{ message }}</p>
        </div>
    </div>
</div>
{% endfor %}

banking-system-master/templates/core/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-gray-800 p-6">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight">Banking System</span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'transactions:transaction_report' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Transaction Report
                </a>
                <a href="{% url 'transactions:deposit_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Deposit
                </a>
                <a href="{% url 'transactions:withdraw_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Withdraw
                </a>
            </div>
            <div>
                <a href="{% url 'accounts:user_logout' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Logout</a>
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'accounts:user_login' %}" class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Login</a>
            </div>
            <div>
                <a href="{% url 'accounts:user_registration' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a>
            </div>
        {% endif %}
    </div>
</nav>